<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Echo  Alexa</name>
   <tag></tag>
   <elementGuidId>473c66ec-7691-4aee-8d93-b8595223144a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(8) > a.hmenu-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmenu-content']/ul/li[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Echo &amp; Alexa&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7d617f1e-67e4-492f-b855-1af029c31dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmenu-item</value>
      <webElementGuid>4f224afe-252f-46f7-977e-d2290de08beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu-id</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a289d475-2575-4921-8885-54b54c1bb7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref-tag</name>
      <type>Main</type>
      <value>nav_em_1_1_1_7</value>
      <webElementGuid>271526a0-268d-4c8b-9300-54d43815dafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Echo &amp; Alexa</value>
      <webElementGuid>efc4cb5d-abae-4a29-af54-7ad4b7c3ab84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmenu-content&quot;)/ul[@class=&quot;hmenu hmenu-visible&quot;]/li[8]/a[@class=&quot;hmenu-item&quot;]</value>
      <webElementGuid>3b78b250-ad5f-47a5-949a-c053bff72a16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-content']/ul/li[8]/a</value>
      <webElementGuid>7667e15b-5a28-4436-9d38-6a51e02dcf75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amazon miniTV- FREE entertainment'])[1]/following::a[1]</value>
      <webElementGuid>ae3c8b72-3d73-426d-875f-bd615ddb881e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Content and Devices'])[1]/following::a[2]</value>
      <webElementGuid>4dc409c4-6925-4a60-8ba9-5eaac8e470cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fire TV'])[1]/preceding::a[1]</value>
      <webElementGuid>d4f5de81-e282-48b7-a663-3c009f46ab47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[314]</value>
      <webElementGuid>3f14c170-72a1-4f7a-a7c1-27158b874c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[8]/a</value>
      <webElementGuid>cb46a7c2-821d-4bef-8186-42a888a4cbeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Echo &amp; Alexa' or . = 'Echo &amp; Alexa')]</value>
      <webElementGuid>8d2f8878-c15d-4c6a-9d66-e2263af913ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
