<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Electronics</name>
   <tag></tag>
   <elementGuidId>6c0eb14e-e95c-49dd-bd49-831a05871146</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-xshop']/a[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;navigation&quot;i >> internal:role=link[name=&quot;Electronics&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>34e173d5-ee95-4efc-913b-a77899ba63ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/electronics/b/?ie=UTF8&amp;node=976419031&amp;ref_=nav_cs_electronics</value>
      <webElementGuid>3e5d4761-5a29-4d03-8375-eb985ea0ebdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-a  </value>
      <webElementGuid>eddf0a7d-a031-4926-be40-35c683cd38a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f66fc89b-9790-4b73-940e-6e6baf77e808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>793b55cf-f487-4174-9db4-a8c2dc76d630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-slot-id</name>
      <type>Main</type>
      <value>nav_cs_5</value>
      <webElementGuid>adc215d2-a96b-4837-aa94-1d4ee7314747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-content-id</name>
      <type>Main</type>
      <value>nav_cs_electronics</value>
      <webElementGuid>b49c62bf-4654-4d8a-91bb-713bd2f68780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>o66pzp-806zv7-fa7c3d-gjpkpu</value>
      <webElementGuid>bf6f32e7-fde1-4a52-9849-c0ef80cb5fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Electronics </value>
      <webElementGuid>16f11c8d-df9f-439d-9abd-fa293fc27d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-xshop&quot;)/a[@class=&quot;nav-a&quot;]</value>
      <webElementGuid>69242b40-63aa-418c-aeac-ec24c2bd43e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-xshop']/a[6]</value>
      <webElementGuid>a5aac5af-bf85-412e-868b-e5cf73b3833f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Electronics')]</value>
      <webElementGuid>7cf79700-db3c-4ab5-8a62-8bc567f67996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobiles'])[1]/following::a[1]</value>
      <webElementGuid>12e97eb4-d863-4154-a919-ea254aeaa848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home &amp; Kitchen'])[2]/preceding::a[1]</value>
      <webElementGuid>09f3ae97-5fe1-4a14-b41e-70d9c5e7c254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prime'])[1]/preceding::a[2]</value>
      <webElementGuid>1742d709-cf70-44e4-becb-9dd6c47694fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/electronics/b/?ie=UTF8&amp;node=976419031&amp;ref_=nav_cs_electronics')]</value>
      <webElementGuid>663df140-6579-44b2-98a5-ab8f8ef5f87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/a[6]</value>
      <webElementGuid>939e60ec-ddf8-49bc-b566-df647f67abaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/electronics/b/?ie=UTF8&amp;node=976419031&amp;ref_=nav_cs_electronics' and (text() = ' Electronics ' or . = ' Electronics ')]</value>
      <webElementGuid>03920b82-946e-42c5-9477-3477f9209e80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
