<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Change countryregion_nav-flyout-buffer-top</name>
   <tag></tag>
   <elementGuidId>d78697ad-7873-4d22-b58b-09497fff9d85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-flyout-icp > div.nav-flyout-buffer-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nav-flyout-icp']/div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#nav-flyout-icp > .nav-flyout-buffer-top</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7a76c929-9377-4f71-ae16-f68f8b0eaa80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-flyout-buffer-top</value>
      <webElementGuid>f706a5af-2e1c-452e-b41a-218ffd868805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-flyout-icp&quot;)/div[@class=&quot;nav-flyout-buffer-top&quot;]</value>
      <webElementGuid>edf65e7f-89df-4b87-bcea-567bb91ca424</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-flyout-icp']/div[5]</value>
      <webElementGuid>e4872d7b-418e-4512-9ff2-a91af2d7c876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[5]</value>
      <webElementGuid>076ca675-7c51-40c0-9d53-384bb2545dc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
