<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuitforDataDrivenTesting2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>61e91c1f-d362-4350-b54a-6637697f3bd1</testSuiteGuid>
   <testCaseLink>
      <guid>7cfdb86a-6a9a-41be-a081-c9b677fe08ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CertificationTestCase/Testcase33</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>877e4fce-6a21-4ad0-893e-0c884137f473</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data2</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>877e4fce-6a21-4ad0-893e-0c884137f473</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Phone</value>
         <variableId>bb2b5e2a-1d3c-4a58-8852-f6f323abdcea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>877e4fce-6a21-4ad0-893e-0c884137f473</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>5118f389-a0f4-411c-a118-c6a58eb56d4c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
