<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Music</name>
   <tag></tag>
   <elementGuidId>a2734e92-dea6-4922-88cd-4e2d084810c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CardInstancei3g2UwVbPvKWh9IPSrml0w']/div[2]/div[17]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Music&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7384765f-f460-44c5-b1f8-d0431e30046d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gp/new-releases/music/ref=zg_bsnr_nav_music_0</value>
      <webElementGuid>fc43c3a5-b6be-4473-8800-5ab23e41c7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Music</value>
      <webElementGuid>0d95936f-0083-4370-a603-6db38a723e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CardInstancei3g2UwVbPvKWh9IPSrml0w&quot;)/div[@class=&quot;_p13n-zg-nav-tree-all_style_zg-browse-group__88fbz&quot;]/div[@class=&quot;_p13n-zg-nav-tree-all_style_zg-browse-item__1rdKf _p13n-zg-nav-tree-all_style_zg-browse-height-small__nleKL&quot;]/a[1]</value>
      <webElementGuid>d79ad918-5f5b-44f5-b0db-5b18e4015067</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CardInstancei3g2UwVbPvKWh9IPSrml0w']/div[2]/div[17]/a</value>
      <webElementGuid>0a4087a6-1c10-4e4b-bc02-599ff67d39db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Music')]</value>
      <webElementGuid>30718f8e-e624-4117-9a64-c7b872444b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Movies &amp; TV Shows'])[2]/following::a[1]</value>
      <webElementGuid>3edd8fd4-9e18-489a-b25e-73370f214a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kindle Store'])[2]/following::a[2]</value>
      <webElementGuid>c59835b4-7e65-42d0-8969-74f3d6b427d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Musical Instruments'])[2]/preceding::a[1]</value>
      <webElementGuid>94fdf6e5-ad98-46c1-a55e-7318798209f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office Products'])[2]/preceding::a[2]</value>
      <webElementGuid>f4238b0d-0061-405c-ad6a-2afed1c8eca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gp/new-releases/music/ref=zg_bsnr_nav_music_0')]</value>
      <webElementGuid>df873e1a-c07c-4676-9f02-a122d49d90e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/a</value>
      <webElementGuid>0551aeba-508f-4645-bf47-be87fb92edfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/gp/new-releases/music/ref=zg_bsnr_nav_music_0' and (text() = 'Music' or . = 'Music')]</value>
      <webElementGuid>7d37b00b-55d1-4e49-8e94-eea75e95602d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
