<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>446b97ad-760e-47e1-b580-1eead2c524a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container']/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/a/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.zlQd20._1eDlvI > img[alt=&quot;Image&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Image Image Best Truewireless Headphones Grab Now&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>21fd942c-a6e7-4d15-85dd-775d5fdec5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static-assets-web.flixcart.com/www/linchpin/batman-returns/images/fk-default-image-75ff340b.png?q=90</value>
      <webElementGuid>b83f186a-cc62-4123-8bfb-72cc954a2991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>ec87ba58-f04f-4570-a7e4-211342387001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Image</value>
      <webElementGuid>07a21e53-77c6-498a-8c7e-3c82edc68087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container&quot;)/div[1]/div[@class=&quot;q8WwEU&quot;]/div[@class=&quot;_3zsGrb&quot;]/div[@class=&quot;_2-LWwB&quot;]/div[1]/div[@class=&quot;css-175oi2r&quot;]/div[@class=&quot;css-175oi2r&quot;]/div[@class=&quot;css-175oi2r r-13awgt0 r-1iqfa7g r-60vfwk&quot;]/div[@class=&quot;css-175oi2r r-13awgt0 r-1iqfa7g r-60vfwk&quot;]/div[@class=&quot;_1ui5b4&quot;]/div[@class=&quot;yAlKeh&quot;]/div[@class=&quot;_2L0uxW&quot;]/div[@class=&quot;_3116_u&quot;]/div[@class=&quot;_1yQHx8 _2UnIQ_ _3ak8Rd _1kAmyc&quot;]/div[1]/div[@class=&quot;css-175oi2r r-13awgt0 r-eqz5dr&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;_3n8fna1ac _3n8fnays _3n8fnan7 _3n8fna1 _3n8fnabm _1i2djtb9 _1i2djt0&quot;]/div[1]/div[@class=&quot;css-175oi2r&quot;]/div[@class=&quot;_3MlEpv&quot;]/div[@class=&quot;tLbyDf&quot;]/div[@class=&quot;_25HC_u&quot;]/div[@class=&quot;css-175oi2r&quot;]/div[1]/div[1]/a[@class=&quot;_3n8fna1ac _3n8fna13p _3n8fnas4 _3n8fna4y _3n8fnagj _1i2djtb9 _1i2djtk9 _1i2djti0 _1i2djt9f _1i2djt76 _1i2djtdi _1i2djtfr _1i2djt2o _1i2djt4x&quot;]/div[@class=&quot;_3n8fna1ac _3n8fnays _3n8fnan7 _3n8fna1 _3n8fnabm _1i2djtb9 _1i2djt0 _1i2djt90 _1i2djt91 _1i2djt92 _1i2djt6r _1i2djt6s _1i2djt6t _1i2djt29 _1i2djt2a _1i2djt2b _1i2djt4i _1i2djt4j _1i2djt4k&quot;]/div[@class=&quot;_3n8fna1ac _3n8fnays _3n8fnan7 _3n8fna1 _3n8fnabm _1i2djtb9 _1i2djt0 _1i2djt90 _1i2djt6r _1i2djt29 _1i2djt4i&quot;]/div[@class=&quot;zlQd20 _1eDlvI&quot;]/img[1]</value>
      <webElementGuid>d8766672-8503-42e0-8e1a-5bea186cff78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/a/div/div/div/img</value>
      <webElementGuid>9ba974ae-46b8-4758-92c2-fe5902395864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Image'])[22]</value>
      <webElementGuid>78a5c43c-a17d-4951-a80a-a409c7f6c729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div/div/img</value>
      <webElementGuid>f7f35806-647d-4731-8226-511ebdb146b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static-assets-web.flixcart.com/www/linchpin/batman-returns/images/fk-default-image-75ff340b.png?q=90' and @alt = 'Image']</value>
      <webElementGuid>1773c048-1fa3-4136-9bc5-d4ba81afd773</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
