<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>a17cfb36-66e5-4825-a13e-461ddfb6e4cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Please rotate your device'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span._30XB9F</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;✕&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ffe4d23a-782f-427f-8133-83e14f338387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c91af856-5404-443c-9d2d-b6867c5b6e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_30XB9F</value>
      <webElementGuid>9525d58b-4c19-4b1f-9eb2-3669d402cc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>✕</value>
      <webElementGuid>a9cab16f-f119-45a3-8a0e-e806ac9bc610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;en-fonts-loaded useInterFont&quot;]/body[@class=&quot;fk-modal-visible&quot;]/div[@class=&quot;fbDBuK _3CYmv5&quot;]/div[@class=&quot;JFPqaw&quot;]/span[@class=&quot;_30XB9F&quot;]</value>
      <webElementGuid>4d2b35e2-ce83-4aa7-a10e-7ce31d4b7f3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please rotate your device'])[1]/following::span[1]</value>
      <webElementGuid>6e2753e0-2c56-4977-bc72-86cfbee53030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flipkart.com'])[1]/following::span[1]</value>
      <webElementGuid>91788ac4-3f26-43be-bba6-9a3b194c35a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[4]/preceding::span[1]</value>
      <webElementGuid>47c60549-8813-4f26-8546-adf6872a901d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Email/Mobile number'])[1]/preceding::span[3]</value>
      <webElementGuid>bc463e47-e891-4df1-a373-d2fac31e7f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='✕']/parent::*</value>
      <webElementGuid>6fc8ceba-cd3b-4bcd-a1f0-61c39648a326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span</value>
      <webElementGuid>ac86f258-fcbf-4959-b3c7-0247800c9b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '✕' or . = '✕')]</value>
      <webElementGuid>9997ac96-02b4-4981-9382-1d4108019f4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
