<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_OLEVS Watches for Men Skeleton Automat_60e5e5</name>
   <tag></tag>
   <elementGuidId>0d898e15-525a-417f-98b1-1c2d92dcbc7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='productTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#productTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#productTitle</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>10337fd9-a51b-427e-b806-31756199753e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productTitle</value>
      <webElementGuid>15ae4404-8b94-450e-95e4-6900e3564545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-size-large product-title-word-break</value>
      <webElementGuid>c9f8237a-1c42-41f2-ad95-871b7b866e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>        OLEVS Watches for Men Skeleton Automatic Mechanical Diamond Self Winding Gold Luxury Wristwatch Luminous Waterproof Business Dress Watch       </value>
      <webElementGuid>e76eb229-110a-4006-8f76-339d91e0d109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productTitle&quot;)</value>
      <webElementGuid>9794fa6d-293d-4ba9-91f1-c62a31c8f0f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='productTitle']</value>
      <webElementGuid>e11394dd-306e-4b03-b940-558e17b82417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h1[@id='title']/span</value>
      <webElementGuid>2866b9fb-fa0f-4d78-bf8e-a25f80f2a890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit the OLEVS Store'])[1]/following::span[1]</value>
      <webElementGuid>a800aa08-6bc0-4050-8a3c-20b5253562e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flash Player'])[1]/following::span[6]</value>
      <webElementGuid>397bb859-4fb6-492a-ba03-f1dd6a122629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/preceding::span[10]</value>
      <webElementGuid>4cdf093a-83bc-4842-a64e-ab0491cfcea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search this page'])[1]/preceding::span[11]</value>
      <webElementGuid>de0415ad-03f4-4633-93c0-8d92d93cf2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OLEVS Watches for Men Skeleton Automatic Mechanical Diamond Self Winding Gold Luxury Wristwatch Luminous Waterproof Business Dress Watch']/parent::*</value>
      <webElementGuid>9f1dd662-a46f-4e0a-be34-f2e3c5751e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>bf0ffe68-c389-4159-b8c7-df088b71de85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'productTitle' and (text() = '        OLEVS Watches for Men Skeleton Automatic Mechanical Diamond Self Winding Gold Luxury Wristwatch Luminous Waterproof Business Dress Watch       ' or . = '        OLEVS Watches for Men Skeleton Automatic Mechanical Diamond Self Winding Gold Luxury Wristwatch Luminous Waterproof Business Dress Watch       ')]</value>
      <webElementGuid>a0f51626-bb53-45ca-9172-831a8354b951</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
