<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Contact Sales_thank-page-icon</name>
   <tag></tag>
   <elementGuidId>001fa56b-38fd-4c5b-877b-1102f952e2b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Sales'])[2]/following::div[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.thank-page-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.thank-page-icon</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dfafecdf-a361-4496-b019-dfe566cc4f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>thank-page-icon</value>
      <webElementGuid>13213273-7207-41d1-b029-5b4533f731aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ThankYouPage&quot;]/div[@class=&quot;main&quot;]/div[@class=&quot;inner typography line&quot;]/div[@class=&quot;thank-you-page-main&quot;]/section[@class=&quot;page-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;thank-page-menu&quot;]/div[@class=&quot;thank-page-icon&quot;]</value>
      <webElementGuid>6e2f9e2b-a749-425f-8ed0-414b56fab76d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Sales'])[2]/following::div[8]</value>
      <webElementGuid>8bf8b10a-6f93-4a3e-980d-bfe6ce4e7786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book a Free Demo'])[2]/following::div[8]</value>
      <webElementGuid>c94eea95-003a-4ce1-8675-b4383bdcfbc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thank you.'])[1]/preceding::div[1]</value>
      <webElementGuid>4ab5fd65-f29f-40c9-92b9-46689e44988a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Requests'])[1]/preceding::div[4]</value>
      <webElementGuid>fca29efa-94ea-430a-be2e-ecba54caeaaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div</value>
      <webElementGuid>ec9cb98e-16ba-406e-9798-0cfc163c449f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
