<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_arrow_forward</name>
   <tag></tag>
   <elementGuidId>f9f02bdd-0b4d-417d-bc45-3f7a3b871aec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='yDmH0d']/c-wiz/div/div/div/div[2]/div/div/div/div/div[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.google-material-icons.giSqbe.fqWlM</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;I'm a business owner or IT administrator Set up a new Workspace account for your business&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>01b90fd3-755e-4451-a4db-0a5b928e847e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>google-material-icons giSqbe fqWlM</value>
      <webElementGuid>7f855e0f-8870-43ae-849b-2c16b243b528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1b57eac9-e9c9-4e1f-94e9-86fc064cf232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>arrow_forward</value>
      <webElementGuid>df046bae-01e0-4214-92b5-69c164d5b97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yDmH0d&quot;)/c-wiz[@class=&quot;SSPGKf&quot;]/div[@class=&quot;T4LgNb&quot;]/div[@class=&quot;kFwPee&quot;]/div[@class=&quot;XwnsH&quot;]/div[@class=&quot;B2pPje&quot;]/div[@class=&quot;K4vxLd-WsjYwc LJdJje&quot;]/div[@class=&quot;K4vxLd-aGsRMb&quot;]/div[@class=&quot;d5NbRd-EScbFb-JIbuQc&quot;]/div[@class=&quot;d8Thnd&quot;]/div[@class=&quot;wwyXq&quot;]/i[@class=&quot;google-material-icons giSqbe fqWlM&quot;]</value>
      <webElementGuid>e2655daa-27c4-4330-b0d3-364af460d8cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='yDmH0d']/c-wiz/div/div/div/div[2]/div/div/div/div/div[2]/i</value>
      <webElementGuid>4ed903e1-efe9-4b6a-b1ec-13fa9b3f9f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set up a new Workspace account for your business'])[1]/following::i[1]</value>
      <webElementGuid>a6603c15-4420-4e39-a091-1d424de1d6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use your work-provided email to sign up for Workspace at no cost'])[1]/preceding::i[1]</value>
      <webElementGuid>01ff5e8d-13b4-4c7f-83d7-e130a4a201ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='arrow_forward']/parent::*</value>
      <webElementGuid>6e436864-3007-4e91-95bd-762b64946f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>bb472bbe-3a37-4ead-bc53-e7b63a92c346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[(text() = 'arrow_forward' or . = 'arrow_forward')]</value>
      <webElementGuid>b0f29a1e-a587-4732-97cf-47e993a5f56e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
